### ISSUE TITLE
Not working in SublimeText 3

### ISSUE THREAD

**Issue by alxkos** [i-akhmadullin/Sublime-CSS3#10]
Hey, this addon not working in sublime text 3. Any reason why?
Thanks

**Comment by i-akhmadullin** [comment]
Did you selected CSS3 syntax as your default for *.css files?

**Comment by alxkos** [comment]
Yes

**Comment by alxkos** [comment]
I had two packages for CSS3 syntax, deleted second one and still not working

**Comment by i-akhmadullin** [comment]
Is there syntax errors or something similar in sublime console?

**Comment by alxkos** [comment]
No, no errors in console

**Comment by i-akhmadullin** [comment]
Is there any chance that you have two CSS3 syntaxes and selected syntax from deleted package?

**Comment by alxkos** [comment]
I will delete both and reinstall this one again and then try
(uninstall using remove package)

**Comment by alxkos** [comment]
log from install
ignored packages updated to: [Vintage, Sublime-CSS3]
found 1 files for base name Default.sublime-theme
found 1 files for base name Default.sublime-theme
generating syntax summary
theme loaded
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage, Sublime-CSS3]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
found 1 files for base name Default.sublime-theme
generating syntax summary
theme loaded
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

And again not working

**Comment by i-akhmadullin** [comment]
`ignored packages updated to: [Vintage, Sublime-CSS3]`

It looks like Sublime-CSS3 is ignored so try to enable it with `Package Control: Enable Package`, restart sublime and check if it fixes bug.

**Comment by alxkos** [comment]
Enabled Vintage and restarted.
Removed addon (css3) restarted and re added it again. 
Still getting an error

ignored packages updated to: [Sublime-CSS3]
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
ignored packages updated to: []
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
generating syntax summary
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by alxkos** [comment]
no disabled packages

**Comment by i-akhmadullin** [comment]
You need to enable Sublime-CSS3 package not Vintage.

**Comment by alxkos** [comment]
I know, but there was only Vintage package to enable.
CSS wasn't there

**Comment by i-akhmadullin** [comment]
This package consists basically of one syntax file, which works identically in st2 and st3 so if you doesn't have syntax errors in console then it can't work because something else blocks or disables plugin.

**Comment by alxkos** [comment]
Any chance I can figure it out?

**Comment by i-akhmadullin** [comment]
Install fresh portable version of sublime, install this plugin and check if it will work to quickly determine if problem is in one of your plugins or in os, system configuration, etc.

Backup sublime data folder, turnoff/remove plugins one by one and restart sublime till something changes. Start from most suspicious and less-known plugins.

**Comment by alxkos** [comment]
I think it's my bad.
syntax is working, but autocomplete not. 
Should it work? Or its only syntax highlighter?

**Comment by i-akhmadullin** [comment]
This plugin is only about syntax highlight, sublime autocomplete is really bad choice for css, there is much better alternatives for smart autocomplete like emmet, hayaku.

**Comment by alxkos** [comment]
thanks, i will check! and sorry for the mess! )
