### ISSUE TITLE
scss support

### ISSUE THREAD

**Issue by ffuubarbuzz** [i-akhmadullin/Sublime-CSS3#11]
It would be grate, if this plugin supports SCSS

**Comment by i-akhmadullin** [comment]
There is already plugins that add scss support to ST:
https://github.com/nathos/sass-textmate-bundle
https://github.com/MarioRicalde/SCSS.tmbundle/tree/SublimeText2

**Comment by ffuubarbuzz** [comment]
actually, I use one of them, and it has no autocomplete for many css3 properties(such as backface-visibility, or even linear-gradient). I thought, your plugin can work in cooperation with that SCSS plugins. Sorry, if I misunderstand how sublime plugins work with each-other.

**Comment by i-akhmadullin** [comment]
This plugin doesn't provide autocomplete for css, it's only adds syntax highlight.

Somehow this is second 'request' for autocomplete(#10) in a last week.
