### ISSUE TITLE
Do not see option for the third step

### ISSUE THREAD

**Issue by jrdn91** [i-akhmadullin/Sublime-CSS3#2]
I installed just as instructed at the bottom of the readme and when I go to the view menu specified and click the "open all future..." link at the top I do not see CSS3 as an option, just CSS. I tried restarting the program and no luck. Is there a way to manually set this up or just through that menu? Or am I possibly doing something wrong?

**Comment by i-akhmadullin** [comment]
Try to update Package Control to latest version and reinstall plugin again. Or just manually clone this repo to `Packages` folder.

**Comment by jrdn91** [comment]
sweet thanks!
